name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - run: ruby -v

    - name: Cache gems
      uses: actions/cache@preview
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-

    - name: Setup bundler
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle config build.nokogiri --use-system-libraries

    - name: Run the tests
      run: ruby validation.rb
